version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mattilda
      POSTGRES_PASSWORD: mattilda
      POSTGRES_DB: mattilda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://mattilda:mattilda@db:5432/mattilda
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend/app
    command: npm run dev
    volumes:
      - ./frontend/app:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: